# DOCS https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
#-------------------------------------------------------------------------------

default: warning

#-MODIFIED SETTINGS-------------------------------------------------------------
blanks-around-headings: { lines_below: 0 } # rule of proximity
ul-style: { style: sublist }
ol-prefix: { style: ordered }
line-length: { tables: false, code_block_line_length: 100 }
no-inline-html: { allowed_elements: [img, details, summary, kbd, a] }

#-DISABLED----------------------------------------------------------------------
ul-indent: false # not compatible with using tabs
no-hard-tabs: false # taken care of by editorconfig
blanks-around-lists: false # space waster
first-line-heading: false # e.g., ignore-comments
no-emphasis-as-heading: false # sometimes useful
